

-- Stored Procedures Lista Deseos Videojuego


CREATE PROCEDURE PA_DELETE_LISTA_DESEOS_VIDEOJUEGO_ByID 
(@ID_CLIENTE int,@ID_PRODUCTO int)
AS 
 	Delete from LISTA_DESEOS_VIDEOJUEGOS
	Where (ID_CLIENTE =  @ID_CLIENTE)  AND (ID_PRODUCTO =  @ID_PRODUCTO)


CREATE PROCEDURE PA_SELECT_LISTA_DESEOS_VIDEOJUEGO_All
 AS 
 	Select ID_CLIENTE ,ID_PRODUCTO  from LISTA_DESEOS_VIDEOJUEGOS


CREATE PROCEDURE PA_SELECT_LISTA_DESEOS_VIDEOJUEGO
(@ID_CLIENTE int,@ID_PRODUCTO int)
AS 
 	Select ID_CLIENTE ,ID_PRODUCTO  from LISTA_DESEOS_VIDEOJUEGOS
	Where (ID_CLIENTE =  @ID_CLIENTE)  AND (ID_PRODUCTO =  @ID_PRODUCTO)



CREATE PROCEDURE PA_SELECT_LISTA_DESEOS_VIDEOJUEGO_ByIdProducto
(@ID_PRODUCTO int)
AS 
 	Select ID_CLIENTE ,ID_PRODUCTO  from LISTA_DESEOS_VIDEOJUEGOS
	Where (ID_PRODUCTO =  @ID_PRODUCTO)


CREATE PROCEDURE PA_SELECT_LISTA_DESEOS_VIDEOJUEGO_ByIdCliente
(@ID_CLIENTE int)
AS 
 	Select ID_CLIENTE ,ID_PRODUCTO  from LISTA_DESEOS_VIDEOJUEGOS
	Where (ID_CLIENTE =  @ID_CLIENTE)


CREATE PROCEDURE PA_INSERT_LISTA_DESEOS_VIDEOJUEGO
 (@ID_CLIENTE int,@ID_PRODUCTO int)
AS 
 insert into LISTA_DESEOS_VIDEOJUEGOS(ID_CLIENTE ,ID_PRODUCTO ) 
 values(@ID_CLIENTE ,@ID_PRODUCTO  )



 CREATE PROCEDURE PA_UPDATE_LISTA_DESEOS_VIDEOJUEGO
(@ID_CLIENTE int, @ID_PRODUCTO int)
AS
	Update LISTA_DESEOS_VIDEOJUEGOS SET ID_CLIENTE = @ID_CLIENTE, 
            ID_PRODUCTO = @ID_PRODUCTO