

-- Stored Procedures Reservacion


CREATE PROCEDURE PA_DELETE_RESERVACION_ByID 
(@ID int)
AS 
 	Delete from RESERVACION
	Where (ID =  @ID)


CREATE PROCEDURE PA_SELECT_RESERVACION_All
 AS 
 	Select ID ,ID_CLIENTE ,ID_PRODUCTO ,ADELANTO  from RESERVACION


CREATE PROCEDURE PA_SELECT_RESERVACION_ByID 
(@ID int)
AS 
 	Select ID ,ID_CLIENTE ,ID_PRODUCTO ,ADELANTO  from RESERVACION
	Where (ID =  @ID)


CREATE PROCEDURE PA_SELECT_RESERVACION_ByIdCliente
(@ID_CLIENTE int)
AS 
 	Select ID ,ID_CLIENTE ,ID_PRODUCTO ,ADELANTO  from RESERVACION
	Where (ID_CLIENTE =  @ID_CLIENTE)


CREATE PROCEDURE PA_INSERT_RESERVACION
 (@ID int,@ID_CLIENTE int,@ID_PRODUCTO int,@ADELANTO money)
AS 
 insert into RESERVACION(ID ,ID_CLIENTE ,ID_PRODUCTO ,ADELANTO ) 
 values(@ID ,@ID_CLIENTE ,@ID_PRODUCTO ,@ADELANTO  )


CREATE PROCEDURE PA_UPDATE_RESERVACION
 (@ID int,@ID_CLIENTE int,@ID_PRODUCTO int,@ADELANTO money)
AS 
 	Update  RESERVACION
	Set 	ID_CLIENTE =  @ID_CLIENTE  ,
	ID_PRODUCTO =  @ID_PRODUCTO  ,
	ADELANTO =  @ADELANTO  
	Where (ID =  @ID)  





