

ALTER PROCEDURE PA_INSERT_VIDEOJUEGO
 (@ID int,@NOMBRE varchar(50),@CANTIDAD_INVENTARIO int,@DESCUENTO int,@ID_CATEGORIA int,@PRECIO_COLONES money,@PRECIO_DOLARES money,
 @DESCRIPCION varchar(50),@FECHA_SALIDA date,@NOTA float, @ESTADO int, @IMAGEN varbinary(MAX))
AS 
 insert into VIDEOJUEGO(ID ,NOMBRE ,CANTIDAD_INVENTARIO ,DESCUENTO ,ID_CATEGORIA ,PRECIO_COLONES ,PRECIO_DOLARES ,DESCRIPCION ,
 FECHA_SALIDA ,NOTA, ESTADO, IMAGEN ) 
 values(@ID ,@NOMBRE ,@CANTIDAD_INVENTARIO ,@DESCUENTO ,@ID_CATEGORIA ,@PRECIO_COLONES ,@PRECIO_DOLARES ,@DESCRIPCION ,
 @FECHA_SALIDA ,@NOTA, @ESTADO, @IMAGEN  ) 


 CREATE PROCEDURE PA_DELETE_VIDEOJUEGO_ByID 
(@ID int)
AS 
 	Delete from VIDEOJUEGO
	Where (ID =  @ID)  


ALTER PROCEDURE PA_UPDATE_VIDEOJUEGO
 (@ID int,@NOMBRE varchar(50),@CANTIDAD_INVENTARIO int,@DESCUENTO int,@ID_CATEGORIA int,@PRECIO_COLONES money,
 @PRECIO_DOLARES money,@DESCRIPCION varchar(50),@FECHA_SALIDA date,@NOTA float, @ESTADO int, @IMAGEN varbinary(MAX))
AS 
 	Update  VIDEOJUEGO
	Set 	NOMBRE =  @NOMBRE  ,
	CANTIDAD_INVENTARIO =  @CANTIDAD_INVENTARIO  ,
	DESCUENTO =  @DESCUENTO  ,
	ID_CATEGORIA =  @ID_CATEGORIA  ,
	PRECIO_COLONES =  @PRECIO_COLONES  ,
	PRECIO_DOLARES =  @PRECIO_DOLARES  ,
	DESCRIPCION =  @DESCRIPCION  ,
	FECHA_SALIDA =  @FECHA_SALIDA  ,
	NOTA =  @NOTA  ,
	ESTADO = @ESTADO,
	IMAGEN = @IMAGEN
	Where (ID =  @ID)  


ALTER PROCEDURE PA_SELECT_VIDEOJUEGO_ByID 
(@ID int)
AS 
 	Select ID ,NOMBRE ,CANTIDAD_INVENTARIO ,DESCUENTO ,ID_CATEGORIA ,PRECIO_COLONES ,PRECIO_DOLARES ,DESCRIPCION ,FECHA_SALIDA ,NOTA, ESTADO, IMAGEN  from VIDEOJUEGO
	Where (ID =  @ID)


ALTER PROCEDURE PA_SELECT_VIDEOJUEGO_All
 AS 
 	Select ID ,NOMBRE ,CANTIDAD_INVENTARIO ,DESCUENTO ,ID_CATEGORIA ,PRECIO_COLONES ,PRECIO_DOLARES ,DESCRIPCION ,FECHA_SALIDA ,NOTA, ESTADO, IMAGEN  from VIDEOJUEGO


CREATE PROCEDURE PA_BORRADO_LOGICO_VIDEOJUEGO
(@ID int)
AS
	UPDATE VIDEOJUEGO
	SET ESTADO = 0
	WHERE ID = @ID


