

-- Stored Procedures Usuario

CREATE PROCEDURE PA_DELETE_USUARIO
(@USUARIO varchar(50))
AS 
 	Delete from USUARIO
	Where (USUARIO =  @USUARIO)


CREATE PROCEDURE PA_SELECT_USUARIO_All
 AS 
 	Select USUARIO ,PASSWORD ,ID_CATEGORIA ,IMAGEN  from USUARIO



CREATE PROCEDURE PA_SELECT_USUARIO_ByUsuario
(@USUARIO varchar(50))
AS 
 	Select USUARIO ,PASSWORD ,ID_CATEGORIA ,IMAGEN  from USUARIO
	Where (USUARIO =  @USUARIO)


CREATE PROCEDURE PA_INSERT_USUARIO
 (@USUARIO varchar(50),@PASSWORD varchar(50),@ID_CATEGORIA int,@IMAGEN varbinary(MAX))
AS 
 insert into USUARIO(USUARIO ,PASSWORD ,ID_CATEGORIA ,IMAGEN ) 
 values(@USUARIO ,@PASSWORD ,@ID_CATEGORIA ,@IMAGEN  )



CREATE PROCEDURE PA_UPDATE_USUARIO
 (@USUARIO varchar(50),@PASSWORD varchar(50),@ID_CATEGORIA int,@IMAGEN varbinary(MAX))
AS 
 	Update  USUARIO
	Set 	PASSWORD =  @PASSWORD  ,
	ID_CATEGORIA =  @ID_CATEGORIA  ,
	IMAGEN =  @IMAGEN  
	Where (USUARIO =  @USUARIO)  




