


-- Stored Procedures Correo


CREATE PROCEDURE PA_INSERT_CORREO
 (@CORREO varchar(50),@ID_CLIENTE int)
AS 
 insert into CORREO(CORREO ,ID_CLIENTE ) 
 values(@CORREO ,@ID_CLIENTE  )


CREATE PROCEDURE PA_UPDATE_CORREO
(@CORREO_VIEJO varchar(50), @ID_CLIENTE_VIEJO int, @CORREO_NUEVO varchar(50), @ID_CLIENTE_NUEVO int)
AS
	Update CORREO
	SET CORREO.CORREO = @CORREO_NUEVO, CORREO.ID_CLIENTE = @ID_CLIENTE_NUEVO
	where CORREO.CORREO = @CORREO_VIEJO and CORREO.ID_CLIENTE = @ID_CLIENTE_VIEJO


CREATE PROCEDURE PA_DELETE_CORREO_ByID 
(@CORREO varchar(50),@ID_CLIENTE int)
AS 
 	Delete from CORREO
	Where (CORREO =  @CORREO)  AND (ID_CLIENTE =  @ID_CLIENTE)


CREATE PROCEDURE PA_SELECT_CORREO_ByID 
(@ID_CLIENTE int)
AS 
 	Select CORREO ,ID_CLIENTE  from CORREO
	Where (ID_CLIENTE =  @ID_CLIENTE)

	
CREATE PROCEDURE PA_SELECT_CORREO_Filter
(@CORREO varchar(50))
AS 
 	Select CORREO ,ID_CLIENTE  from CORREO
	Where (CORREO =  @CORREO)


CREATE PROCEDURE PA_SELECT_CORREO_All
 AS 
 	Select CORREO ,ID_CLIENTE  from CORREO




