

-- Stored Procedures FacturaVideojuego

CREATE PROCEDURE InsertarEncabezadoVideojuego
(@ID int, @FECHA_ORDEN date, @ID_CLIENTE int, @TOTAL money, @SUBTOTAL money)
AS
	insert into ORDEN_COMPRA_VIDEOJUEGO values (@ID, @FECHA_ORDEN, @ID_CLIENTE, @TOTAL, @SUBTOTAL)


CREATE PROCEDURE InsertarDetalleVideojuego
(@ID_ORDEN int, @ID_DETALLE int, @ID_PRODUCTO int, @CANTIDAD int, @TOTAL_DETALLE money)
AS
	Insert into DETALLE_VIDEOJUEGO values (@ID_ORDEN, @ID_DETALLE, @ID_PRODUCTO, @CANTIDAD, @TOTAL_DETALLE )


CREATE PROCEDURE RestarCantidadVideojuego
(@ID int, @CANTIDAD int)
AS
	Update VIDEOJUEGO
    SET CANTIDAD_INVENTARIO = CANTIDAD_INVENTARIO - @CANTIDAD
    where ID = @ID


CREATE PROCEDURE GetFacturaVideojuego
(@IdOrdenCompra int)
AS
	Select ORDEN_COMPRA_VIDEOJUEGO.ID, ORDEN_COMPRA_VIDEOJUEGO.FECHA_ORDEN, ORDEN_COMPRA_VIDEOJUEGO.ID_CLIENTE, 
	ORDEN_COMPRA_VIDEOJUEGO.TOTAL, ORDEN_COMPRA_VIDEOJUEGO.SUBTOTAL, DETALLE_VIDEOJUEGO.ID_ORDEN, DETALLE_VIDEOJUEGO.ID_DETALLE, 
	DETALLE_VIDEOJUEGO.ID_PRODUCTO, DETALLE_VIDEOJUEGO.CANTIDAD, DETALLE_VIDEOJUEGO.TOTAL
    from ORDEN_COMPRA_VIDEOJUEGO INNER JOIN DETALLE_VIDEOJUEGO ON ORDEN_COMPRA_VIDEOJUEGO.ID = DETALLE_VIDEOJUEGO.ID_ORDEN
    where ORDEN_COMPRA_VIDEOJUEGO.ID = @IdOrdenCompra
	