

-- Stored Procedures Producto


ALTER PROCEDURE PA_INSERT_PRODUCTO
 (@ID int, @DESCRIPCION varchar(50),@CANTIDAD_INVENTARIO int,@DESCUENTO money,@ID_CATEGORIA int,@PRECIO_COLONES money,@PRECIO_DOLARES money,@IMAGEN varbinary(MAX), @ESTADO int)
AS 
 insert into PRODUCTO(ID ,DESCRIPCION ,CANTIDAD_INVENTARIO ,DESCUENTO ,ID_CATEGORIA ,PRECIO_COLONES ,PRECIO_DOLARES ,IMAGEN, ESTADO ) 
 values(@ID ,@DESCRIPCION ,@CANTIDAD_INVENTARIO ,@DESCUENTO ,@ID_CATEGORIA ,@PRECIO_COLONES ,@PRECIO_DOLARES ,@IMAGEN, @ESTADO  )


CREATE PROCEDURE PA_DELETE_PRODUCTO_ByID 
(@ID int)
AS 
 	Delete from PRODUCTO
	Where (ID =  @ID)


ALTER PROCEDURE PA_UPDATE_PRODUCTO
 (@ID int,@DESCRIPCION varchar(50),@CANTIDAD_INVENTARIO int,@DESCUENTO money,@ID_CATEGORIA int,@PRECIO_COLONES money,@PRECIO_DOLARES money,@IMAGEN varbinary(MAX), @ESTADO int)
AS 
 	Update  PRODUCTO
	Set 	DESCRIPCION =  @DESCRIPCION  ,
	CANTIDAD_INVENTARIO =  @CANTIDAD_INVENTARIO  ,
	DESCUENTO =  @DESCUENTO  ,
	ID_CATEGORIA =  @ID_CATEGORIA  ,
	PRECIO_COLONES =  @PRECIO_COLONES  ,
	PRECIO_DOLARES =  @PRECIO_DOLARES  ,
	IMAGEN =  @IMAGEN  ,
	ESTADO = @ESTADO
	Where (ID =  @ID)  


CREATE PROCEDURE PA_DISMINUIR_CANTIDAD_PRODUCTO
(@ID int)
AS
	UPDATE PRODUCTO
	Set CANTIDAD_INVENTARIO= CANTIDAD_INVENTARIO - 1
	WHERE ID = @ID


CREATE PROCEDURE PA_AUMENTAR_CANTIDAD_PRODUCTO
(@ID int)
AS
	UPDATE PRODUCTO
	Set CANTIDAD_INVENTARIO= CANTIDAD_INVENTARIO + 1
	WHERE ID = @ID


ALTER PROCEDURE PA_SELECT_PRODUCTO_ByID 
(@ID int)
AS 
 	Select ID ,DESCRIPCION ,CANTIDAD_INVENTARIO ,DESCUENTO ,ID_CATEGORIA ,PRECIO_COLONES ,PRECIO_DOLARES ,IMAGEN, ESTADO  from PRODUCTO
	Where (ID =  @ID)
	

ALTER PROCEDURE PA_SELECT_PRODUCTO_ByDescripcion 
(@filtro varchar(50))
AS 
 	Select ID ,DESCRIPCION ,CANTIDAD_INVENTARIO ,DESCUENTO ,ID_CATEGORIA ,PRECIO_COLONES ,PRECIO_DOLARES ,IMAGEN, ESTADO  from PRODUCTO
	Where (DESCRIPCION = @filtro)


ALTER PROCEDURE PA_SELECT_PRODUCTO_All
 AS 
 	Select ID, DESCRIPCION ,CANTIDAD_INVENTARIO ,DESCUENTO ,ID_CATEGORIA ,PRECIO_COLONES ,PRECIO_DOLARES ,IMAGEN, ESTADO  from PRODUCTO


CREATE PROCEDURE PA_BORRADO_LOGICO_PRODUCTO
(@ID int)
AS
	UPDATE PRODUCTO
	SET ESTADO = 0
	WHERE ID = @ID



